---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# learnB4SS

<!-- badges: start -->
<!-- badges: end -->

This is the R package for the workshop *Learn Bayesian Analysis for the Speech Sciences*.

We will add more info here soon and instructions to install this package, so stay tuned!

For now, you can have a look at the FAQs below and make sure you have gone through the installation of brms [here](https://learnb4ss.github.io/learnB4SS/articles/install-brms.html).

## FAQs

### I live in an inconvenient time-zone. Will I be able to attend at a different time?

We are sorry we could not accommodate all time-zones, but we will provide you with captioned recordings so that you can watch them and follow along.

We are still finalising the practical aspects of how we will share the recordings and in what form. We will update this FAQ as soon as possible.

### On macOS, I get errors related to the Command Line Tools. What can I do?

The following might work (but no garantee). Open the Terminal and run the following code.

```shell
sudo rm -rf /Library/Developer/CommandLineTools
sudo rm -rf /usr/local/include
xcode-select --install
```

### Do I need to know how to use R in order to participate?

Yes. While we will guide you through the process of running a Bayesian analysis with a lot of examples, we won't go over the basics of R.

If you wish to brush up your R skills, we recommend the interactive tool `swiRl`, which you can find here: <http://swirlstats.com/>.

### Do I need a basic knowledge of statistics?

Yes. We will give you the necessary notions to understand and perform a Bayesian analysis, and we will revise a few concepts from non-Bayesian statistics, but we expect you to have familiarity with linear regressions.

In particular, we won't cover topics such as interpreting regression coefficients, understanding interactions, including random effects, or coding factors.

For an easy-to-follow introduction, we highly recommend Bodo Winter's book *Statistic for linguists: An introduction using R* (which also includes a chapter on basic R).
